// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJxcQwwB6pf9dqOiwPmb5q_1efAX9ujVQ',
    appId: '1:187605378876:android:67b435b3e0f70ef625e039',
    messagingSenderId: '187605378876',
    projectId: 'cast-acac5',
    storageBucket: 'cast-acac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw8AtgkwGWVI7C9ckZLNC2I3Z-QGwR_jA',
    appId: '1:187605378876:ios:74ab2c500dd9b04a25e039',
    messagingSenderId: '187605378876',
    projectId: 'cast-acac5',
    storageBucket: 'cast-acac5.appspot.com',
    androidClientId: '187605378876-oguooqnaqgt8p2k2g9ipkenjvh2tp3sb.apps.googleusercontent.com',
    iosClientId: '187605378876-aitqgpk86tshnkjtb2pukj0c7bokfea4.apps.googleusercontent.com',
    iosBundleId: 'com.ecom.app.ecom',
  );
}
